-- ===== Milestone 7b: Store pre-generated PDF signed URL in session =====
-- Add column to store the signed URL (generated by teacher when selecting presentation)
alter table sessions add column if not exists pdf_signed_url text;

-- Update get_active_session to return the pre-generated signed URL
drop function if exists get_active_session(text);
create or replace function get_active_session(code text)
returns table (
  id uuid,
  room_code text,
  created_at timestamptz,
  current_presentation_id uuid,
  presentation_title text,
  pdf_path text,
  pdf_signed_url text
)
language sql stable security definer as $$
  select s.id, s.room_code, s.created_at,
         s.current_presentation_id, p.title, p.pdf_path, s.pdf_signed_url
  from sessions s
  left join presentations p on p.id = s.current_presentation_id
  where s.room_code = code and s.status = 'active'
  limit 1
$$;

revoke all on function get_active_session(text) from public;
grant execute on function get_active_session(text) to anon;